---

# a place to drop start and stop scripts
- name: ensure 
  file:
    path:  "{{ scripts_home }}"
    state: directory
    owner: "{{ oracle_user }}" 
    group: "{{ oracle_group }}"
    mode:  0700
