---

# a place to drop start and stop scripts
- name: slick scripts folder
  file:
    path: "{{ scripts_home }}"
    state: absent
    
- name: create scripts folder
  file: 
    path:  "{{ scripts_home }}" 
    mode:  0700
    owner: "{{ oracle_user }}" 
    group: "{{ oracle_group }}"
    state: directory
    
- name: check for domain home already installed
  stat: path="{{ domain_home }}"
  register: domain_home_var

- name: create the security folder for boot.properties
  file: path="{{ domain_home }}/servers/AdminServer/security" state=directory mode=0750

- name: copy over the boot.properties file
  template: src=../templates/boot.properties.j2 dest="{{ domain_home }}/servers/AdminServer/security/boot.properties" mode=0660

- name: template over the start-admin script
  template: 
    src:   start-admin.py.j2
    dest:  "{{ scripts_home }}/start-admin.py" 
    owner: "{{ oracle_user }}" 
    group: "{{ oracle_group }}" 
    mode:  0700

- name: template over the stop-admin script
  template: 
    src:   stop-admin.py.j2
    dest:  "{{ scripts_home }}/stop-admin.py" 
    owner: "{{ oracle_user }}" 
    group: "{{ oracle_group }}" 
    mode:  0700

- name: Copy wls-admin systemd script
  template: 
    src:  ../templates/wls-admin.service.j2 
    dest: /etc/systemd/system/wls-admin.service 
    mode: 0644
  become: yes
  become_user: root

- name: Enable wls-admin as linux service
  service: 
    name: wls-admin
    enabled: true
    state: restarted
  become: yes
  become_user: root
